name: daily_verse
description: "A daily bible verse reviewer."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  nb_utils: ^7.0.6
  path: ^1.9.0
  path_provider: ^2.1.5
  flex_color_scheme: ^8.0.0
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0-pre
  device_info_plus: ^11.1.0
  lottie: ^3.1.3
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.1
  # loading_overlay: ^0.4.2
  logger: ^2.4.0
  entry: ^1.0.0
  flutter_animate: ^4.5.0
  uuid: ^4.5.1
  device_preview: ^1.2.0
  firebase_core: ^3.7.0
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1
  internet_connection_checker_plus: ^2.5.2
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  home_widget: ^0.7.0
  expansion_tile_group: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_native_splash: ^2.4.2
  objectbox_generator: any

flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/anims/
    - assets/icon/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
    - family: Madimi
      fonts:
        - asset: assets/fonts/MadimiOne-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package



#! native_splash
# dart run flutter_native_splash:create
flutter_native_splash:
  # background_image: "assets/splash/bg_light.png"
  # background_image_dark: "assets/splash/bg_dark.png"
  color: "#AF1740"
  color_dark: "#740938"
  # image: "assets/icon/icon_round.png"
  # image_dark: "assets/icon/icon_round.png"
  android_12:
    # background_image: "assets/splash/bg_light.png"
    # background_image_dark: "assets/splash/bg_dark.png"
    # image: "assets/icon_foreground.png"
    # image_dark: ""
    color: "#AF1740"
    color_dark: "#740938"
    # image: "assets/icon/icon_round.png"
    # image_dark: "assets/icon/icon_round.png"